config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'

  resources :usuarios
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  resources :restaurantes
  
  match 'ola' => 'ola_mundo#index', via: 'get'
  root 'static_pages#home'
end

app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
    before_action :set_qualificacao, only: [:show, :edit, :update, :destroy]
    
    # GET /qualificacoes
    # GET /qualificacoes.json
    def index
        @qualificacoes = Qualificacao.all
    end
    
    # GET /qualificacoes/1
    # GET /qualificacoes/1.json
    def show
    end
    
    # GET /qualificacoes/new
    def new
        preparar_form
        @qualificacao = Qualificacao.new
        if params[:cliente]
            @qualificacao.cliente = Cliente.find(params[:cliente])
        end
        if params[:restaurante]
            @qualificacao.restaurante = Restaurante.find(params[:restaurante])
        end
    end
    
    # GET /qualificacoes/1/edit
    def edit
        preparar_form
    end
    
    # POST /qualificacoes
    # POST /qualificacoes.json
    def create
        @qualificacao = Qualificacao.new(qualificacao_params)
        
        respond_to do |format|
            if @qualificacao.save
                format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully created.' }
                format.json { render :show, status: :created, location: @qualificacao }
            else
                preparar_form
                format.html { render :new }
                format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # PATCH/PUT /qualificacoes/1
    # PATCH/PUT /qualificacoes/1.json
    def update
        respond_to do |format|
            if @qualificacao.update(qualificacao_params)
                format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully updated.' }
                format.json { render :show, status: :ok, location: @qualificacao }
            else
                preparar_form
                format.html { render :edit }
                format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /qualificacoes/1
    # DELETE /qualificacoes/1.json
    def destroy
        @qualificacao.destroy
        respond_to do |format|
            format.html { redirect_to qualificacoes_url, notice: 'Qualificacao was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualificacao
        @qualificacao = Qualificacao.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def qualificacao_params
        params.require(:qualificacao).permit(:cliente_id, :restaurante_id, :nota, :valor_gasto)
    end

    private
    def preparar_form
        @clientes = Cliente.order :nome
        @restaurantes = Restaurante.order :nome
    end
end

app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

app/views/qualificacoes/_form.html.erb
<%= form_with(model: qualificacao, local: true) do |form| %>
    <% if qualificacao.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>
            <ul>
                <% qualificacao.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <!-- <%= form.label :cliente_id %> -->
        <% if @qualificacao.cliente %>
            <%= form.hidden_field 'cliente_id' %>
        <% else %>
            <p><%= form.label :cliente_id %>
                <%= form.collection_select(:cliente_id, @clientes, 
                    :id, :nome, :prompt => true) %></p>
            <!-- <%= form.number_field :cliente_id, id: :qualificacao_cliente_id %> -->
        <% end %>
    </div>

    <div class="field">
        <!-- <%= form.label :restaurante_id %> -->
        <% if @qualificacao.restaurante %>
            <%= form.hidden_field 'restaurante_id' %>
        <% else %>
            <p><%= form.label :restaurante_id %>
                <%= form.collection_select(:restaurante_id, @restaurantes,
                    :id, :nome, :prompt => true) %></p>
        <% end %>
        <!-- <%= form.number_field :restaurante_id, id: :qualificacao_restaurante_id %> -->
    </div>

    <div class="field">
        <%= form.label :nota %>
        <%= form.text_field :nota, id: :qualificacao_nota %>
    </div>

    <div class="field">
        <%= form.label :valor_gasto %>
        <%= form.text_field :valor_gasto, id: :qualificacao_valor_gasto %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/qualificacoes/edit.html.erb
<h1>Editing Qualificacao</h1>

<%= render 'form', qualificacao: @qualificacao %>

<%= link_to 'Show', @qualificacao %> |
<%= link_to 'Back', qualificacoes_path %>

app/views/qualificacoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qualificacoes</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Restaurante</th>
      <th>Nota</th>
      <th>Valor gasto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualificacoes.each do |qualificacao| %>
      <tr>
        <!-- <td><%= qualificacao.cliente_id %></td>
        <td><%= qualificacao.restaurante_id %></td> -->
        <td><%= qualificacao.cliente.nome %></td>
        <td><%= qualificacao.restaurante.nome %></td>
        <td><%= qualificacao.nota %></td>
        <td><%= valor_formatado(qualificacao.valor_gasto) %></td>
        <td><%= link_to 'Show', qualificacao %></td>
        <td><%= link_to 'Edit', edit_qualificacao_path(qualificacao) %></td>
        <td><%= link_to 'Destroy', qualificacao, 
            method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualificacao', new_qualificacao_path %>

app/views/qualificacoes/new.html.erb
<h1>New Qualificacao</h1>

<%= render 'form', qualificacao: @qualificacao %>

<%= link_to 'Back', qualificacoes_path %>

app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <!-- <%= @qualificacao.cliente_id %> -->
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <strong>Restaurante:</strong>
  <!-- <%= @qualificacao.restaurante_id %> -->
  <%= @qualificacao.restaurante.nome %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @qualificacao.nota %>
</p>

<p>
  <strong>Valor gasto:</strong>
  <%= valor_formatado(@qualificacao.valor_gasto) %>
</p>

<%= comentarios @qualificacao %>
<%= novo_comentario @qualificacao %>

<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacoes_path %>